site_name: MyPsych
site_url: http://127.0.0.1:8000/
site_author: Cameron White
site_description: A active website that stores case studies related to the International Bacurraletee (IB) Psychology.
repo_name: RestiveSole267/MyPsych
repo_url: https://github.com/RestiveSole267/MyPsych


theme: 
  name: material
  features:
    - navigation.tabs
  
  include_search_page: false
  search_index_only: true

  language: en

markdown_extensions:
  - admonition
  - footnotes


plugins:
  - search:
      separator: '[\s\-]+'
  - awesome-pages
  - git-revision-date-localized
